services:
  - type: web
    name: facturini
    runtime: docker
    plan: starter
    healthCheckPath: /up
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: facturini-db
          property: connectionString

databases:
  - name: facturini-db
    databaseName: facturini_production
    plan: free